# Generated by Django 2.2.1 on 2019-07-21 20:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190721_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability_area',
            field=models.CharField(help_text="Examples: 'Rhône-Alpes' or 'Around Grenoble, Chambéry, Lyon' or 'All the french Alpes'", max_length=250, verbose_name='availability area (further details)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability_area_geo',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Click on the map to build the area where you like to go out in the mountains.', null=True, srid=4326, verbose_name='availability area'),
        ),
    ]
