# Generated by Django 2.1.3 on 2018-12-02 22:07

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20181202_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.user_directory_path_pict),
        ),
    ]
