# Generated by Django 2.2.1 on 2019-07-22 12:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190721_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability_area_geo',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Click on the map to build the area where you are available for going out in the mountains.', null=True, srid=4326, verbose_name='availability area'),
        ),
    ]
