# Generated by Django 2.1.3 on 2018-12-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20181202_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability_area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='list_of_courses',
            field=models.TextField(blank=True),
        ),
    ]
