# Generated by Django 2.2.1 on 2019-08-19 12:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190722_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Click on the map to show where you live.', null=True, srid=4326, verbose_name='location'),
        ),
    ]
