# Generated by Django 2.1.3 on 2018-12-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20181203_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability_area',
            field=models.CharField(max_length=250),
        ),
    ]
