# Generated by Django 2.1.3 on 2018-12-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-last_update'], 'verbose_name': 'profil'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Utilisée pour indiquer votre âge sur votre profil publique.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, help_text='Prenez le temps de rédiger une présentation concise et vendeuse ! Les 200 premiers caractères apparaissent dans la liste des profils donc soignez-les :)'),
        ),
    ]
