# Generated by Django 2.2.4 on 2019-08-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability_area',
            field=models.CharField(blank=True, help_text="Examples: 'Rhône-Alpes' or 'Around Grenoble, Chambéry, Lyon' or 'All the french Alpes'.", max_length=250, null=True, verbose_name='availability area (further details)'),
        ),
    ]
