# Generated by Django 2.1.3 on 2018-12-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20181214_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability_area',
            field=models.CharField(help_text="Exemple : 'Rhône-Alpes' ou 'Autour de Grenoble' ou 'Toutes les Alpes'", max_length=250, verbose_name='zone de disponibilité'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, help_text='Prenez le temps de rédiger une présentation concise et vendeuse ! Les 200 premiers caractères apparaissent dans la liste des profils donc soignez-les :)', verbose_name='présentation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='list_of_courses',
            field=models.TextField(blank=True, verbose_name='liste de courses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_profile',
            field=models.BooleanField(default=True, verbose_name='profile public'),
        ),
    ]
