# Generated by Django 2.2.4 on 2019-08-23 14:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20190823_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability_area_geo',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text="Click on the map to build the area where you are available for going out in the mountains. Tip: click on 'Shift' key while you draw to activate freehand drawing.", null=True, srid=4326, verbose_name='availability area'),
        ),
    ]
