# Generated by Django 2.2.4 on 2019-10-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_name_it'),
        ('profiles', '0010_auto_20190823_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grades',
            field=models.ManyToManyField(blank=True, to='activities.Grade', verbose_name='grades'),
        ),
    ]
