# Generated by Django 2.1.3 on 2018-12-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20181217_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability_area',
            field=models.CharField(help_text="Exemples : 'Rhône-Alpes' ou 'Autour de Grenoble, Chambéry, Lyon' ou 'Toutes les Alpes'", max_length=250, verbose_name='zone de disponibilité'),
        ),
    ]
