# Generated by Django 2.2.6 on 2020-03-02 14:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your phone number with your calling country code (Fr +33 | It +39 | Sp +34 | UK +44). Ex: write +33600000000 instead of 0600000000.', max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
    ]
