# Generated by Django 2.1.3 on 2018-12-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20181220_2316'),
        ('profiles', '0013_auto_20181220_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grades',
            field=models.ManyToManyField(blank=True, null=True, to='activities.Grade', verbose_name='activités'),
        ),
    ]
