# Generated by Django 2.1.3 on 2018-12-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grades',
            field=models.ManyToManyField(blank=True, to='activities.Grade', verbose_name='activités'),
        ),
    ]
