# Generated by Django 4.0.3 on 2022-04-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20220329_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('it', 'Italian')], default='fr', max_length=30),
        ),
    ]
