# Generated by Django 2.1.3 on 2018-12-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20181220_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grades',
            field=models.ManyToManyField(blank=True, to='activities.Grade', verbose_name='cotations'),
        ),
    ]
