# Generated by Django 2.1.3 on 2018-12-21 20:10

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20181221_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'base user', 'verbose_name_plural': 'base users'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-last_update'], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grades',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_profile',
            field=models.BooleanField(default=False, verbose_name='profile status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activities',
            field=models.ManyToManyField(to='activities.Activity', verbose_name='activities'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability_area',
            field=models.CharField(help_text="Exemples: 'Rhône-Alpes' ou 'Around Grenoble, Chambéry, Lyon' ou 'All the french Alpes'", max_length=250, verbose_name='availability area'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Used to display your age on your public profile. Exemple: 05/25/2000', null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, help_text='Take your time to write a concise introduction that makes people want to know your better! The first 200 characters are displayed in the profile list ;)', verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='list_of_courses',
            field=models.TextField(blank=True, verbose_name='list of courses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.user_directory_path_pict, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_profile',
            field=models.BooleanField(default=True, help_text='Quand votre profil est public il apparait dans la liste des profils.', verbose_name='public profile'),
        ),
    ]
