# Generated by Django 4.0.3 on 2022-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_customuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('it', 'Italian')], default='fr', help_text='Language that will be used in the email we will send to you.', max_length=30, verbose_name='language'),
        ),
    ]
