# Generated by Django 4.0.3 on 2022-04-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_profile_profile_inactivity_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_inactivity_email_sent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='inactivity_email_sent',
            field=models.JSONField(default=list),
        ),
    ]
