# Generated by Django 4.0.3 on 2022-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_remove_profile_profile_inactivity_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='inactivity_email_sent',
            field=models.JSONField(default=list, verbose_name='inactivity email sent'),
        ),
    ]
