# Generated by Django 4.0.3 on 2022-04-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_customuser_inactivity_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='inactivity_email_sent',
            field=models.JSONField(blank=True, default=list, verbose_name='inactivity email sent'),
        ),
    ]
