# Generated by Django 2.2.1 on 2019-05-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name_it',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
