# Generated by Django 2.2.6 on 2019-11-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_name_it'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['activity__name'], 'verbose_name': 'grade', 'verbose_name_plural': 'grades'},
        ),
        migrations.AddField(
            model_name='grade',
            name='ordering',
            field=models.PositiveIntegerField(default='1', verbose_name='ordering'),
            preserve_default=False,
        ),
    ]
