# Generated by Django 2.1.3 on 2018-12-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20181220_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'activité', 'verbose_name_plural': 'activités'},
        ),
        migrations.AddField(
            model_name='activity',
            name='grades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Grade', verbose_name='cotations'),
        ),
    ]
