# Generated by Django 2.2.6 on 2019-11-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20191114_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['activity__name', 'ordering'], 'verbose_name': 'grade', 'verbose_name_plural': 'grades'},
        ),
        migrations.AddField(
            model_name='grade',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_it',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
