# Generated by Django 2.1.3 on 2018-12-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20181220_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='grades',
        ),
    ]
