# Generated by Django 2.1.3 on 2018-12-20 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_activity_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='activity',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='activities.Activity', verbose_name='activité'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nom'),
        ),
    ]
