# Generated by Django 2.1.3 on 2018-12-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20181220_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name': 'activité', 'verbose_name_plural': 'activités'},
        ),
    ]
