# Generated by Django 2.1.3 on 2018-12-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20181220_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'grade', 'verbose_name_plural': 'grades'},
        ),
    ]
