# Generated by Django 2.2.4 on 2019-10-20 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0002_activity_name_it'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateField(verbose_name='start')),
                ('end_date', models.DateField(verbose_name='end')),
                ('activities', models.ManyToManyField(blank=True, to='activities.Activity', verbose_name='activities')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'availability',
                'verbose_name_plural': 'availabilities',
                'ordering': ['start_date'],
            },
        ),
    ]
