# Generated by Django 2.2.1 on 2019-05-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="70 characters max.<br>Exemple: 'Meije Crossing - Normal route - Bivouac at the Grand Pic'.", max_length=70, verbose_name='title')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(help_text='Take the time to write concise description that makes people want to join you!', verbose_name='description')),
                ('start_date', models.DateField(help_text='Exemple: 25/05/2020', verbose_name='start')),
                ('end_date', models.DateField(verbose_name='end')),
                ('topo_link', models.URLField(blank=True, help_text="<a href='https://www.camptocamp.org/' target='_blank'>Camptocamp</a> and <a href='https://www.summitpost.org/' target='_blank'>SummitPost</a> are a high quality source of topos.", verbose_name='URL link to the outing topo')),
                ('activities', models.ManyToManyField(to='activities.Activity', verbose_name='activities')),
            ],
            options={
                'verbose_name': 'outing',
                'verbose_name_plural': 'outings',
                'ordering': ['start_date'],
            },
        ),
    ]
