# Generated by Django 2.1.3 on 2018-12-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0002_outing_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outing',
            options={'ordering': ['start_date'], 'verbose_name': 'sortie'},
        ),
    ]
