# Generated by Django 2.1.3 on 2018-12-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0004_auto_20181214_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='c2c_link',
            field=models.URLField(blank=True, verbose_name='lien Camptocamp'),
        ),
        migrations.AlterField(
            model_name='outing',
            name='description',
            field=models.TextField(help_text='Prenez le temps de rédiger une description concise et vendeuse !', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='outing',
            name='end_date',
            field=models.DateField(verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='outing',
            name='start_date',
            field=models.DateField(verbose_name='début'),
        ),
        migrations.AlterField(
            model_name='outing',
            name='title',
            field=models.CharField(help_text='50 caractères max', max_length=50, verbose_name='titre'),
        ),
    ]
