# Generated by Django 2.1.3 on 2018-12-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0008_auto_20181216_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='c2c_link',
            field=models.URLField(blank=True, help_text="Ce champ est important car il améliore la lecture de votre sortie par les internautes. <a href='https://www.camptocamp.org/' target='_blank' >Camptocamp</a> est une très bonne source de topos.", verbose_name='lien URL vers un topo de la sortie'),
        ),
    ]
