# Generated by Django 2.1.3 on 2018-12-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0009_auto_20181216_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outing',
            old_name='c2c_link',
            new_name='topo_link',
        ),
    ]
