# Generated by Django 2.1.3 on 2018-12-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0011_auto_20181216_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='title',
            field=models.CharField(help_text="60 caractères max. Soyez précis pour que votre sortie apparaissent dans les recherches par mots-clés. Exemples : 'Traversée de la Meije par la voie normale. Bivouac Grand Pic' ou 'Vol rando Grand Arc (Lauzière) - Attero de Montlamb'air (Saint-Jean-de-la-Porte)'", max_length=60, verbose_name='titre'),
        ),
    ]
