# Generated by Django 2.1.3 on 2018-12-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0013_auto_20181216_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='title',
            field=models.CharField(help_text="60 caractères max. Exemple : 'Traversée de la Meije - Voie normale - Bivouac Grand Pic'", max_length=60, verbose_name='titre'),
        ),
    ]
