# Generated by Django 2.1.3 on 2018-12-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0015_auto_20181216_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='title',
            field=models.CharField(help_text="Exemple : 'Traversée de la Meije - Voie normale - Bivouac Grand Pic'. 70 caractères max.", max_length=70, verbose_name='titre'),
        ),
    ]
