# Generated by Django 2.1.3 on 2018-12-17 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0017_auto_20181217_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='activities',
            field=models.ManyToManyField(to='activities.Activity', verbose_name='activités'),
        ),
        migrations.AlterField(
            model_name='outing',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='auteurs'),
        ),
    ]
