# Generated by Django 2.1.3 on 2018-12-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0018_auto_20181217_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='start_date',
            field=models.DateField(help_text='Exemple : 25/05/2020', verbose_name='début'),
        ),
    ]
