# Generated by Django 2.1.3 on 2018-12-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0019_auto_20181220_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outing',
            options={'ordering': ['start_date'], 'verbose_name': 'outing', 'verbose_name_plural': 'outings'},
        ),
        migrations.AlterField(
            model_name='outing',
            name='description',
            field=models.TextField(help_text='Take the time to write concise description that makes people want to join you!', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='outing',
            name='title',
            field=models.CharField(help_text="70 characters max.<br>Exemple: 'Meije Crossing - Normal route - Bivouac at the Grand Pic'.", max_length=70, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='outing',
            name='topo_link',
            field=models.URLField(blank=True, help_text="<a href='https://www.camptocamp.org/' target='_blank'>Camptocamp</a> and <a href='https://www.summitpost.org/' target='_blank'>SummitPost</a> are a high quality source of topos.", verbose_name='URL link to the outing topo'),
        ),
    ]
